var IsMobileView=null;$(document).ready(function(){localStorage.setItem("Updated","false");IsMobileView=$("#Mobilecheck").val();if(IsMobileView!="False")
{appendUtmParamKundaliOp.initiate();}
var x=getCookie("Username");if(x!=""){$('#divAppBanner').hide();}
else
{setTimeout(function(){$('#divAppBanner').slideDown(2000);},10000);}
var myString=$("#IPValue").val();if(myString==null||myString==""||myString==''||myString=='undefined')
{$("#Kund_PhoneCode").val("91 (IN)");}
else
{var result=contained(myString,countries);$("#Kund_PhoneCode").val(result);}});$(window).scroll(function(event){var height=$("#OnlineAstrologerLoadHeight").height();var scrollTop=$(window).scrollTop();if(scrollTop>=height)
{LoadOnlineAstrologer();}})
function LoadOnlineAstrologer()
{var chkload=localStorage.getItem("Updated");if(chkload!="true")
{$.ajax({type:"GET",url:"/home/loadonlineastrologervc",data:{},success:function(response)
{if(response)
{$("#LoadOnlineAstrologer").hide();$("#OnlineAstrologer").html(response);localStorage.setItem("Updated","true");}
else
{$("#LoadOnlineAstrologer").show();}},failure:function(e){}})}}
function fncCloseAppDownloadBanner()
{$("#divAppBanner").hide();var _bannercookie=getCookie("Username");if(_bannercookie=="")
{var user="close";setCookie("Username",user,30)}}
function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+"; "+expires;}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return "";}
$(function(){var dt=new Date();var year=dt.getFullYear()+10;var range='1920:'+year;$("#Kund_Dateofbirth").datepicker({changeMonth:true,yearRange:range,changeYear:true,dateFormat:'dd/mm/yy'});});if($("#Mobilecheck").val()=="False")
{$("#Kund_BirthTime").datetimepicker({format:"LTS"}).on("dp.change",function(e){}),document.querySelector("#kundliRegistrationFrm").addEventListener("submit",function(e){if($("#Kund_MobileError").hide(),$("#errorKundalimsg").hide(),$(this).valid()){e.preventDefault();var t=$("#kundliRegistrationFrm"),n=$('input[name="__RequestVerificationToken"]',t).val(),i={Kund_Name:$("#Kund_Name").val(),Kund_Dateofbirth:$("#Kund_Dateofbirth").val(),Kund_EmailAddress:$("#Kund_EmailAddress").val(),Kund_BirthTime:$("#Kund_BirthTime").val(),Kund_BirthPlace:$("#Kund_BirthPlace").val(),Kund_PhoneNumber:$("#Kund_PhoneNumber").val(),Kund_PhoneCode:$("#Kund_PhoneCode").val(),Kund_UtmCampaign:$("#Kund_UtmCampaign").val(),Kund_UtmSource:$("#Kund_UtmSource").val(),Kund_UtmContent:$("#Kund_UtmContent").val(),Kund_UtmMedium:$("#Kund_UtmMedium").val(),Kund_UtmTerm:$("#Kund_UtmTerm").val(),Kund_Latitude:$("#Kund_Latitude").val(),Kund_Longitude:$("#Kund_Longitude").val(),Kund_Timezone:$("#Kund_Timezone").val(),__RequestVerificationToken:n,SignUpType:"KundliRegistration"};if(CountryId=i.Kund_PhoneCode.match(/\(([^)]+)\)/)[1],""!=CountryId){var d=new RegExp("^[0-9]{10}$"),u=new RegExp("^[0-9]");if("IN"===CountryId||"US"===CountryId||"CA"===CountryId){if(null==i.Kund_PhoneNumber||!d.test(i.Kund_PhoneNumber))return $("#Kund_MobileError").show(),$("#Kund_PhoneNumber-error").hide(),$("#Kund_MobileError").html("Enter 10 digit mobile number"),!1;$("#Kund_MobileError").hide()}else{if(!(i.Kund_PhoneNumber.length>3&&i.Kund_PhoneNumber.length<17&&u.test(i.Kund_PhoneNumber)))return $("#Kund_MobileError").show(),$("#Kund_PhoneNumber-error").hide(),$("#Kund_MobileError").html("Enter your valid mobile number"),!1;$("#Kund_MobileError").hide()}}
var a=$("#kundliRegistrationFrm").find("[type='submit']").text();if($("#kundliRegistrationFrm").find("[type='submit']").text("Please wait.."),$("#kundliRegistrationFrm").find("[type='submit']").attr("disabled",!0),"True"==Isuser)return void
$.ajax({type:"POST",url:"/contentsyn/kundli/kundliresults",data:i,success:function(e){e.success?($("#kundliRegistrationFrm").find("[type='submit']").text("Redirecting.."),window.location=e.redirectUrl+"?Kund_Name="+e.data.kund_Name+"&Kund_Dateofbirth="+e.data.kund_Dateofbirth+"&Kund_BirthTime="+e.data.kund_BirthTime+"&Kund_Longitude="+e.data.kund_Longitude+"&Kund_Latitude="+e.data.kund_Latitude+"&Kund_Timezone="+e.data.kund_Timezone):($("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a),$("#errorKundalimsg").show().text(e.message))},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}});$.ajax({type:"POST",url:"/contentsyn/kundli/kundlitilepagenew",data:i,success:function(e){e.success?($("#kundliRegistrationFrm").find("[type='submit']").text("Redirecting.."),window.location=e.redirectUrl+"?Kund_Name="+e.data.kund_Name+"&Kund_Dateofbirth="+e.data.kund_Dateofbirth+"&Kund_BirthTime="+e.data.kund_BirthTime+"&Kund_Longitude="+e.data.kund_Longitude+"&Kund_Latitude="+e.data.kund_Latitude+"&Kund_Timezone="+e.data.kund_Timezone):($("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a),$("#errorKundalimsg").show().text(e.message))},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});}
var appendUtmParamKundaliOp={initiate:function(){$.when(astroyogiUtmParamOps.utmParamSetStat).then(function(){var e=astroyogiUtmParamOps.getUtmParam();null!=e&&($("#Kund_UtmSource").val(e.utmSource),$("#Kund_UtmCampaign").val(e.utmCampaign),$("#Kund_UtmContent").val(e.utmContent),$("#Kund_UtmMedium").val(e.utmMedium),$("#Kund_UtmTerm").val(e.utmTerm))})}};var array=null;$('#Kund_BirthPlace').keyup(function(){if($("#Kund_BirthPlace").val().length>=1){$.ajax({type:"GET",url:"/staticdata/getgeolocationasync",data:{_searchText:$("#Kund_BirthPlace").val()},success:function(result){if(result.success==true){array=result.data;var jsonString=JSON.parse(JSON.stringify(result.data));$('#Kund_BirthPlace').autocomplete({source:$.map(jsonString,function(item){return item.location+","+item.state+","+item.countryCode;}),select:function(event,ui){var nameArr=ui.item.value.split(',');var details=array.filter(x=>x.location===nameArr[0]&&x.state===nameArr[1]&&x.countryCode===nameArr[2])[0];if(details.latitute==null||details.latitute==''||details.latitute=='undefined')
{details.latitute="19.076";details.longitutde="72.8777";details.timeZone="5.2";}
$("#Kund_Latitude").val(details.latitute);$("#Kund_Longitude").val(details.longitutde);$("#Kund_Timezone").val(details.timeZone);if(details.timeZone==null)
{n=details.latitute,i=details.longitutde;var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_Timezone").val(t)}}},a.send()}
var selectecItem=jsonString.filter(function(value){$("#Kund_BirthPlace").val(ui.item.value);});},});}
else
{$.getScript('https://maps.googleapis.com/maps/api/js?key=AIzaSyCWFvWQ9BYo6UBtX0hA8QxSv-wq1485ttE&libraries=places',function()
{googlihitcheck=1;initialize();});}},failure:function(e){$("#kundliRegistrationFrm").find("[type='submit']").removeAttr("disabled"),$("#kundliRegistrationFrm").find("[type='submit']").text(a)}})}});function initialize(){var e=new google.maps.places.Autocomplete(document.getElementById("Kund_BirthPlace"),{types:["(cities)"]});google.maps.event.addListener(e,"place_changed",function(){$("#Kund_Latitude").val(""),$("#Kund_Longitude").val(""),$("#Kund_Timezone").val("");var t=e.getPlace(),n=t.geometry.location.lat(),i=t.geometry.location.lng();$("#Kund_Latitude").val(n),$("#Kund_Longitude").val(i);var d=new Date,u="https://maps.googleapis.com/maps/api/timezone/json?location="+n+","+i+"&timestamp="+(d.getTime()/1e3+60*d.getTimezoneOffset())+"&key=AIzaSyCFuOlkFwvEa9kplV3RP7wnbtQHmSvZMsQ",a=new XMLHttpRequest;a.open("GET",u),a.onload=function(){if(200===a.status){var e=JSON.parse(a.responseText);if("OK"==e.status){var t=(e.dstOffset+e.rawOffset)/3600;$("#Kund_Timezone").val(t)}}},a.send()})}
var countries=["91 (IN)","1 (US)","1 (CA)","61 (AU)","971 (AE)","44 (GB)","93 (AF)","355 (AL)","213 (DZ)","1684 (AS)","376 (AD)","244 (AO)","1264 (AI)","0 (AQ)","1268 (AG)","54 (AR)","374 (AM)","297 (AW)","43 (AT)","994 (AZ)","1242 (BS)","973 (BH)","880 (BD)","1246 (BB)","375 (BY)","32 (BE)","501 (BZ)","229 (BJ)","1441 (BM)","975 (BT)","591 (BO)","387 (BA)","267 (BW)","0 (BV)","55 (BR)","246 (IO)","673 (BN)","359 (BG)","226 (BF)","257 (BI)","855 (KH)","237 (CM)","238 (CV)","1345 (KY)","236 (CF)","235 (TD)","56 (CL)","86 (CN)","61 (CX)","672 (CC)","57 (CO)","269 (KM)","242 (CG)","242 (CD)","682 (CK)","506 (CR)","225 (CI)","385 (HR)","53 (CU)","357 (CY)","420 (CZ)","45 (DK)","253 (DJ)","1767 (DM)","1809 (DO)","593 (EC)","20 (EG)","503 (SV)","240 (GQ)","291 (ER)","372 (EE)","251 (ET)","500 (FK)","298 (FO)","691 (FM)","679 (FJ)","358 (FI)","33 (FR)","594 (GF)","689 (PF)","0 (TF)","241 (GA)","220 (GM)","995 (GE)","49 (DE)","233 (GH)","350 (GI)","30 (GR)","299 (GL)","1473 (GD)","590 (GP)","1671 (GU)","502 (GT)","224 (GN)","245 (GW)","592 (GY)","509 (HT)","0 (HM)","39 (VA)","504 (HN)","852 (HK)","36 (HU)","354 (IS)","62 (ID)","98 (IR)","964 (IQ)","353 (IE)","972 (IL)","39 (IT)","1876 (JM)","81 (JP)","962 (JO)","7 (KZ)","254 (KE)","686 (KI)","965 (KW)","996 (KG)","856 (LA)","371 (LV)","961 (LB)","266 (LS)","231 (LR)","218 (LY)","423 (LI)","370 (LT)","352 (LU)","853 (MO)","389 (MK)","261 (MG)","265 (MW)","60 (MY)","960 (MV)","223 (ML)","356 (MT)","692 (MH)","596 (MQ)","222 (MR)","230 (MU)","269 (YT)","52 (MX)","373 (MD)","377 (MC)","976 (MN)","1664 (MS)","212 (MA)","258 (MZ)","95 (MM)","264 (NA)","674 (NR)","977 (NP)","31 (NL)","599 (AN)","687 (NC)","64 (NZ)","505 (NI)","227 (NE)","234 (NG)","683 (NU)","672 (NF)","850 (KP)","1670 (MP)","47 (NO)","968 (OM)","92 (PK)","680 (PW)","970 (PS)","507 (PA)","675 (PG)","595 (PY)","51 (PE)","63 (PH)","0 (PN)","48 (PL)","351 (PT)","1787 (PR)","974 (QA)","262 (RE)","40 (RO)","70 (RU)","250 (RW)","290 (SH)","1869 (KN)","1758 (LC)","508 (PM)","1784 (VC)","684 (WS)","378 (SM)","239 (ST)","966 (SA)","221 (SN)","381 (CS)","248 (SC)","232 (SL)","65 (SG)","421 (SK)","386 (SI)","677 (SB)","252 (SO)","27 (ZA)","0 (GS)","82 (KR)","34 (ES)","94 (LK)","249 (SD)","597 (SR)","47 (SJ)","268 (SZ)","46 (SE)","41 (CH)","963 (SY)","886 (TW)","992 (TJ)","255 (TZ)","66 (TH)","670 (TL)","228 (TG)","690 (TK)","676 (TO)","1868 (TT)","216 (TN)","90 (TR)","7370 (TM)","1649 (TC)","688 (TV)","256 (UG)","380 (UA)","1 (UM)","598 (UY)","998 (UZ)","678 (VU)","58 (VE)","84 (VN)","1284 (VG)","1340 (VI)","681 (WF)","212 (EH)","967 (YE)","38 (YO)","260 (ZM)","263 (ZW)"];var el=document.getElementById("Kund_PhoneCode");if(el)
{autocomplete(document.getElementById("Kund_PhoneCode"),countries);}